"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

target = 0

def brute_force(n):
    # return sum of even valued fibonacci series
    result = 0
    next = 1
    prev = 1

    while next < n:
        prev, next = next, prev + next
        
        if next % 2 == 0:
            result += next

    return result

def finonnaci_sum(n):
    a = 1
    b = 1
    c = a + b
    sum = 0

    while c < n:
        sum += c
        a = b + c
        b = c + a
        c = a + b

    return sum

def execute(n):
    result = finonnaci_sum(n)
    print ("input: %i output: %i" %(n, result))
    
if __name__ == '__main__':
    execute(4000000)

